# -*- coding: utf-8 -*-
"""sort_object.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Robot702/90ee50cd534deb69fa17a3628871c04a/6352500731.ipynb
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse': [200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}

sorted_obj = sorted(obj_detected.items(), key=lambda x: x[1][0])

for item in sorted_obj:
    print(item)